#!/usr/bin/python

import requests
import datetime
from datetime import timedelta
import dateutil.parser
import requests
import time
import pigpio
import ephem

moon =   [  True,    False,    False,    False,     True]
blues  = [(0, 0), (20, 80), (65, 80), (95, 15), (100, 0)]
whites = [(0, 0), (20, 70), (65, 70), (95, 0), (100, 0)]

bluePins = [22, 24]
whitePins = [14, 25]

pi = pigpio.pi()

def getSuntimes():
    home = ephem.Observer()
    home.lat  = '52.135317'
    home.long = '5.031910'
    home.elevation = 3
    home.date = datetime.datetime.now().strftime('%Y/%m/%d')
    
    sun = ephem.Sun()
    sun.compute(home)

    return (home.next_rising(sun).datetime() + timedelta(hours=1), home.next_setting(sun).datetime() + timedelta(hours=1))

def getMoonphasePercentage():
    now = datetime.datetime.now().date()
    prev = ephem.previous_new_moon(now).datetime().date()
    next = ephem.next_new_moon(now).datetime().date()

    daysThisCycle = (next - prev).days

    percentage = (now - prev).days / float(daysThisCycle) / 2
    if percentage > 50:
        return (50 - (percentage - 50)) * 2
    else:
        return percentage * 2

def getLightPercentage(currentTime, dayStart, dayEnd):
    totalSecondsThisDay = (dayEnd - dayStart).total_seconds()
    currentSecondsThisDay = (currentTime - dayStart).total_seconds()

    percentageOfTheDay = currentSecondsThisDay / totalSecondsThisDay * 100
    print percentageOfTheDay

    blueSetting = getPercentageFromTimeline(blues, percentageOfTheDay)
    whiteSetting = getPercentageFromTimeline(whites, percentageOfTheDay)
    return (blueSetting, whiteSetting)

def getPercentageFromTimeline(timeline, currentTime):
    start = False
    end = False
    for (time, percentage) in timeline:
        if time < currentTime:
            start = (time, percentage)

    for (time, percentage) in timeline[::-1]:
        if time > currentTime:
            end = (time, percentage)

    if start == False or end == False:
        return -1

    endNormalized = end[0] - start[0]
    currentNormalized = currentTime - start[0]

    timePercentage = currentNormalized / endNormalized

    valueDelta = end[1] - start[1]

    return start[1] + (valueDelta * timePercentage)

def setupLights(pi, bluePins, whitePins):
    allPins = bluePins + whitePins
    for pin in allPins:
        pi.set_mode(pin, pigpio.OUTPUT)
        pi.set_PWM_range(pin, 250)
        pi.set_PWM_frequency(pin, 100)

def setLight(pi, pins, percentage):
    value = 250 * (percentage / 100.0)
    for pin in pins:
        pi.set_PWM_dutycycle(pin, value)
def sendPercentagesToApi(whitePercentage, bluePercentage):
    data = {
        "date": datetime.datetime.now().isoformat("T"),
        "valueWhite": whitePercentage,
        "valueBlue": bluePercentage,
    }
    try:
        r = requests.put("http://reef.xeli.eu/api/lights", json=data)
        print r.text
    except requests.exceptions.RequestException as e:
        print "Connection error"
        print e

setupLights(pi, bluePins, whitePins)

while True:
    moonPercentage = getMoonphasePercentage()
    sunrise = datetime.datetime.now().replace(hour=6, minute=30)
    sunset = datetime.datetime.now().replace(hour=21, minute=00)
    (blue, white) = getLightPercentage(datetime.datetime.now(), sunrise, sunset)
    if blue == -1 or white == -1:
        setLight(pi, bluePins, moonPercentage * 1)
        setLight(pi, whitePins, 0)
        sendPercentagesToApi(0, moonPercentage * 1)
    else:
        setLight(pi, bluePins, blue)
        setLight(pi, whitePins, white)
        sendPercentagesToApi(white, blue)
    time.sleep(60)
