#!/usr/bin/python

from relay import *
import json
import pprint
import time
import datetime
import time
from dateutil import parser

configFilePath = "relayTimers.conf"

configString = open(configFilePath)
config = json.load(configString)

for relaySetting in config["relays"]:
    relaySetting["start"] = parser.parse(relaySetting["start"]).time()
    relaySetting["end"] = parser.parse(relaySetting["end"]).time()
    setupRelayOUT(relaySetting["id"])

while True:
    currentTime = datetime.datetime.now().time()
    for relaySetting in config["relays"]:
        currentlyInPeriod = currentTime > relaySetting["start"] and currentTime < relaySetting["end"]
        if currentlyInPeriod:
            newState = relaySetting["stateOnDuringPeriod"]
        else:
            newState = not relaySetting["stateOnDuringPeriod"]
        print "toggle at %s to state: %s" % (currentTime, newState)
        setRelay(relaySetting["id"], newState)
    time.sleep(60 * 5)
