#!/bin/sh

logDir=`pwd`/logs

sudo ./ato >> $logDir/ato.log 2>&1 &
echo "Started ATO: $!"
./temperature >> $logDir/temperature.log 2>&1 &
echo "Started Temperature: $!"

cd ph
sudo ./pHReader >> $logDir/ph.log 2>&1 &
echo "Started PH: $!"
